version: "3.9"
services:
  discovery:
    build: ../../discovery-server
    ports:
      - "8761:8761"
    image: "discovery-server"
  carreservation_A:
    build: ../../CarReservation
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.cloud.config.uri=http://config:8888
    ports:
      - "8300:8300"
    image: "car-reservation"
  event-room-reservation_A:
    build: ../../EventRoomReservation
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.cloud.config.uri=http://config:8888
    ports:
      - "8301:8301"
    image: "event-room-reservation-ms"
  flightReservation_A:
    build: ../../FlightReservation
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.cloud.config.uri=http://config:8888
    ports:
      - "8302:8302"
    image: "flight-reservation"
  reservationrestau_A:
    build: ../../reservation-resto
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.cloud.config.uri=http://config:8888
    ports:
      - "8303:8303"
    image: "reservation-restau"
  chambrereservation_A:
    build: ../../CambreReservation
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.cloud.config.uri=http://config:8888
    ports:
      - "8304:8304"
    image: "chambre-reservation"
  nodejs_ms:
    build: ../../nodejs-ms
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=discovery
    ports:
      - "5000:5000"
    image: "nodejs-ms"
  config:
    build: ../../config-server
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./src/main/resources/centralRepo
        target: /config
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.profiles.active=native
    ports:
      - "8888:8888"
    image: "config-server"
  gateway:
    build: ../../zuul-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8762:8762"
    image: "gateway-server"
