version: "3.9"
services:
  discovery:
    build:  ../../discovery-server
    ports:
      - "8761:8761"
    image: "discovery-server"
  job_A:
    build: ../../job-MS
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.cloud.config.uri=http://config:8888
    ports:
      - "8182:8180"
    image: "job-service"
  candidate_B:
    build:  ../../candidateMS
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.cloud.config.uri=http://config:8888
    ports:
      - "3000:8080"
    image: "candidate-service"
    depends_on:
      - job_A
  candidate_C:
    build:  ../../candidateMS
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.cloud.config.uri=http://config:8888
    ports:
      - "3001:8080"
    image: "candidate-service"
    depends_on:
      - job_A
  nodejs_ms:
    build: ../../nodejs-ms
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=discovery
    ports:
      - "3100:3100"
    image: "nodejs-ms"

  config:
    build: ../../config-server
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./src/main/resources/centralRepo
        target: /config
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.profiles.active=native
    ports:
      - "8888:8888"
    image: "config-server"
  gateway:
    build: ../../zuul-server
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8762:8762"
    image: "gateway-server"